### ISSUE TITLE
Automatic GPS coordinates (geolocation) does not work when using Google Spreadsheets

### ISSUE THREAD

**Issue by Sep-source** [EFRAG-EU/Digital-Template-to-XBRL-Converter#4]
Place:
--> Tab 'general information'
--> B1 list of sites 
--> GPS Coordinates

 Issue:
Geolocation is supposed to be automatically calculated but doesn't seem to work. Also the link to Openstreetmap doesnt work nor the technical sheet. 

![Image](https://github.com/user-attachments/assets/10837600-66d8-4536-b0e8-a8696a2ea10d)
![Image](https://github.com/user-attachments/assets/cf07d52e-cb92-41ae-a04d-b4dcd527f88d)

[VSME-Digital-Template-latest.xlsx](https://github.com/user-attachments/files/20481814/VSME-Digital-Template-latest.xlsx)

**Comment by richieeeeeeee** [comment]
I guess this feature is not supported by Google Spreadsheets, it only works when using MS Excel. But you can of course insert the location manually, using Google Maps or Open Streetmap.

**Comment by richieeeeeeee** [comment]
We updated the Readme and the webpage with a note that functionality might be limited in other spreadsheet applications.

**Comment by Sep-source** [comment]
Hi again - I tested this now in an Excel and the geolocation is still not working. Please see attached the file:

[VSME-Digital-Template-latest_test.xlsx](https://github.com/user-attachments/files/20488368/VSME-Digital-Template-latest_test.xlsx)
